/*
 * This source file was generated by the Gradle 'init' task
 */
package fr.umrae.matsim_noisemodelling;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.sql.SQLException;

import static org.junit.jupiter.api.Assertions.*;

class NoiseModellingTest {
    @Test void testRunNoiseModelling() throws SQLException, IOException {
        String[] args = {"--help"};
        RunNoiseModelling.main(args);
        // Check that the main method runs without throwing an exception
        assertTrue(true);
    }
}
